apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  ports:
    - name: client
      port: 9092
  selector:
    app: kafka
    server-id: "1"
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  ports:
    - name: client
      port: 9093
      targetPort: 9092
  selector:
    app: kafka
    server-id: "2"
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
spec:
  ports:
    - name: client
      port: 9094
      targetPort: 9092
  selector:
    app: kafka
    server-id: "3"
  type: LoadBalancer
